name: "Deploy Azure Infra"

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Deploy Azure infra
      id: deploy_step
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          .\azure\resources\RunDeployment.ps1 -initConfigFile .\azure\configs\init-${{ env.ENVIRONMENT }}.json -mainConfigFile .\azure\configs\main-${{ env.ENVIRONMENT }}.json