name: "Deploy Azure Infra"

inputs: 
  environment:
    required: true
  tenant:
    required: true
  teknologi:
    required: true
  aks:
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Deploy Azure infra
      id: deploy_step
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          $deployTeknologi = '${{ inputs.teknologi }}'
          $deployAKS = '${{ inputs.aks }}'
          if($deployTeknologi -eq 'true'){
            .\azure\resources\RunDeployment.ps1 -configFile .\azure\configs\main-${{ inputs.tenant }}-${{ inputs.environment }}.jsonc
          }
          if($deployAKS -eq 'true'){
            .\azure\resources\RunDeployment.ps1 -configFile .\azure\configs\aks-${{ inputs.tenant }}-${{ inputs.environment }}.jsonc -deployAKS $true -deployMain $false
          }