name: "Deploy Azure Infra"

inputs: 
  environment:
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Deploy Azure infra
      id: deploy_step
      env:
        environment: ${{ inputs.environment }}
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          $environment = '${{ inputs.environment }}'
          write-host $env:environment
          write-host $environment
          $initConfigFile = ".\azure\configs\init-" + $environment + ".json"
          write-host $initConfigFile
          $mainConfigFile = ".\azure\configs\main-" + $environment + ".json"
          write-host $mainConfigFile

          .\azure\resources\RunDeployment.ps1 -initConfigFile $initConfigFile -mainConfigFile $mainConfigFile