name: "Get Module information"

inputs: 
  module:
    required: true
  deployment:
    required: true 
outputs:
  moduleFilePath:
    description: "The file path for the module"
    value: ${{ steps.get_info.outputs.moduleFilePath }}
  moduleFolderPath:
    description: "The folder path for the module"
    value: ${{ steps.get_info.outputs.moduleFolderPath }}

runs:
  using: "composite"
  steps:
    - name: Get module information
      id: get_info
      shell: pwsh
      run: |
        $module = '${{ inputs.module }}'
        $deployment = '${{ inputs.stage }}'
        $moduleFilePath = ".\azure\resources\" + $deployment + "-modules\" + $module + "\main.bicep"
        $moduleFolderPath = ".\azure\resources\" + $deployment + "-modules\" + $module + "\"
        Write-Output ('{0}={1}' -f 'moduleFilePath', $moduleFilePath)
        Write-Output ('{0}={1}' -f 'moduleFilePath', $moduleFilePath) >> $env:GITHUB_OUTPUT
        Write-Output ('{0}={1}' -f 'moduleFolderPath', $moduleFolderPath)
        Write-Output ('{0}={1}' -f 'moduleFolderPath', $moduleFolderPath) >> $env:GITHUB_OUTPUT