name: "Deploy Nginx Ingress"

inputs: 
  clustername:
    required: true
  resourcegroup:
    required: true

runs:
  using: "composite"
  steps:
    #- name: Azure Login
    #  uses: azure/login@v1
    #  with:
    #    creds: ${{ env.AZURE_CREDENTIALS }}
    #    enable-AzPSSession: true
    #- name: Get AKS context
    #  uses: azure/aks-set-context@v3
    #  with:
    #    cluster-name: ${{ inputs.clustername }}
    #    resource-group: ${{ inputs.resourcegroup }}
    #    admin: 'true'
    #    use-kubelogin: 'false'
    - name: Configure Nginx Ingress
      shell: bash
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx \
          --version 4.6.0 \
          --create-namespace \
          --install \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
          --set controller.service.externalTrafficPolicy=Local
        