name: "Deploy Nginx Ingress"

runs:
  using: "composite"
  steps:
    - name: Configure Nginx Ingress
      shell: bash
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx \
          --version 4.6.0 \
          --create-namespace \
          --install \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
          --set controller.service.externalTrafficPolicy=Local
        