name: "Create parameter file"

inputs: 
  moduleFolderPath:
    description: "The path to the module folder"
    required: true
  moduleFileName:
    description: "The filename for the module"
    required: true
  deploymentConfigFile:
    description: "The deployment config file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create parameter file
      id: create-param-file
      shell: pwsh
      run: |
        $deploymentConfigFile = '${{ inputs.deploymentConfigFile }}'
        $deploymentConfigFile = Get-Content $deploymentConfigFile 
        $config = $deploymentConfigFile -replace '(?m)(?<=^([^"]|"[^"]*")*)//.*' -replace '(?ms)/\*.*?\*/' | ConvertFrom-Json

        $template = "./" + '${{ inputs.moduleFileName }}'

        $newJson = [ordered]@{
          '$schema'      = 'https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#'
          contentVersion = "1.0.0.0"
          metadata       = @{template = '$($template)'}
          parameters     = 
          @{
            'config' = @{'value' = $config }
          }
        }
        $paramFile = (Join-Path '${{ inputs.moduleFolderPath }}' "main.parameters.json")
        Set-Content -Path $paramFile -Value (ConvertTo-Json $newJson -Depth 100) -Confirm:$false