name: Release - On push to master

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/automation-account"
  
jobs:
  deploy-resources:
    uses: ./.github/workflows/release-deployresources.yaml
    with:
      environment: prd
    secrets: inherit