name: Release - Deploy resources

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      teknologi:
        type: boolean
        required: true
        default: true
      aks:
        type: boolean
        required: true
        default: false
  
jobs:
  DeployInfra:
    name: "Deploy Azure Infra"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: "Deploy Azure Infra"
      uses: ./.github/actions/templates/infrastructure-deploy-azure-resources
      with:
        environment: ${{ inputs.environment }}
        teknologi: ${{ inputs.teknologi }}
        aks: ${{ inputs.aks }}
      env:
        AZURE_CREDENTIALS: ${{ secrets.BICEP_GITHUBACTIONS_TEKNOLOGI }}