name: Release - On push to main

on:
  push:
    branches:
      - main
      - feature/fixpushmaster
  
jobs:
  deploy-resources:
    uses: ./.github/workflows/release-deployresources.yaml
    with:
      environment: prd
      teknologi: true
      aks: false
    secrets: inherit