name: Release - On push to main

on:
  push:
    branches:
      #- main
      - test
  
jobs:
  deploy-resources:
    uses: ./.github/workflows/release-deployresources.yaml
    with:
      environment: prd
    secrets: inherit