name: On Pull request

on:
  pull_request:
    branches:
      - main

env:
  configFile: ./azure/configs/tst.jsonc

jobs:
  scan-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create parameter file
        uses: ./.github/actions/templates/create-parameter-file
        id: create-parameter-file
        with: 
          moduleFolderPath: ./azure/resources/
          moduleFileName: main.bicep
          deploymentConfigFile: ${{ env.configFile }}
      - name: PSRule validation
        uses: ./.github/actions/templates/validate-module-psrule
        with:
          moduleFolderPath: ./azure/resources/
          psrulePath: "./azure/resources/psrule"